- cur_sbn/css-n-includes/incl_top.inc
> maintenance banner

- cur_sbn/css-n-includes/incl_top.inc
> 'remove' maintenance banner from Mon afternoon

- cur_sbn/data_sb/target_asteroids.shtml
> fixed typo in target link

- cur_sbn/css-n-includes/incl_top.inc
> Friday brief outage announcement

- cur_sbn/css-n-includes/incl_top.inc
> remove maintenance banner

- cur_sbn/index.shtml
> changed release date

- cur_sbn/index.shtml
> minor  code typos

- cur_sbn/data_sb/target_asteroids.shtml
> removed to LORRI datsets from under Pluto

- css-n-includes/incl_top.inc
> Added maintenance banner for 11 Jan outage

- css-n-includes/incl_top.inc
edited incl_top.inc to remove the 11 Jan outage banner
> removed outage banner

- feedback/README.txt
- feedback/js/config.js
- feedback/js/feedback.js
- feedback/recaptcha-v3-verify.php
updated to new version sent out on 28 Mar
> update to v1.3.0

- css-n-includes/incl_top.inc
- feedback/js/config.js
Removed the commented out link so it doesn't show up weird on the feedback pop-up box. 
Doublechecked code snippet that goes into header.
> Tweaking feedback widget

- data_sb/missions/deepspace1/index.shtml
Bad link to USGS archive of MICAS instrument. Tried searching for alternate link. Contacted USGS. Trent Hare responded. Best solution is to remove sentence but contact them when migrating this data. I've commented out the sentence.
> commented out bad link

- feedback/js/feedback.js
Lines of code modified according to instructions supplied by C. Suh to disable recaptcha, which does not work in the SBN/UMD environment for reasons that could not be determined.
> Modify feedback.js to Disable Recaptcha

- data_sb/comet_type.shtml
- data_sb/missions/dart/index.shtml
- data_sb/target_asteroids.shtml
- index.shtml
DART data release for 4/26 per Tilden
> DART edits

- index.shtml
CSS = Customer Satisfaction Survey announcement and banner removed
> remove the PDS CSS

- proposals/ROSES.shtml
- proposals/ROSES2022.shtml
Fixed text to remove reference to PDART.
> removed PDART ref

- data_sb/missions/bopps/index.shtml
- data_sb/missions/cassini/index.shtml
- data_sb/missions/cioc/index.shtml
- data_sb/missions/galileo/index.shtml
- data_sb/missions/hayabusa/index.shtml
- data_sb/missions/hayabusa2/index.shtml
- data_sb/missions/sakigake/index.shtml
- data_sb/missions/stardust/index.shtml
- data_sb/missions/suisei/index.shtml
- data_sb/missions/vega1/index.shtml
- data_sb/missions/vega2/index.shtml
- data_sb/missions/vikingorbiter/index.shtml
Several of the mission pages had bad or changed links to the mission websites
> updates to mission links

- data_sb/missions/cioc/index.shtml
> added na for CIOC mission

- data_sb/comet_type.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_other.shtml
- index.shtml
per email, change nh-a-.... v4 to v5 for ALICE, LEISA, LORRI, MVIC,PEPSSI, SDC, SWAP; v3 to v4 for REX
> NH K4 L2/3 Release 2022-08-11

- data_sb/comet_type.shtml
- data_sb/missions/soho/index.shtml
- data_sb/target_comets.shtml
- index.shtml
v2 to v3 of SOHO SWAN Derived Water
> SOHO v2 to v3

- about/about_SBN.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/missions/nh-kem/index.shtml
- index.shtml
- proposals/ROSES.shtml
- proposals/ROSES2006.shtml
- proposals/ROSES2007.shtml
- proposals/ROSES2008.shtml
- proposals/ROSES2009.shtml
- proposals/ROSES2010.shtml
- proposals/ROSES2011.shtml
- proposals/ROSES2012.shtml
- proposals/ROSES2013.shtml
- proposals/ROSES2014.shtml
- proposals/ROSES2015.shtml
- proposals/ROSES2016.shtml
- proposals/ROSES2017.shtml
- proposals/ROSES2018.shtml
- proposals/ROSES2019.shtml
- proposals/ROSES2020.shtml
- proposals/ROSES2021.shtml
- proposals/ROSES2022.shtml
-- forgot to add NH K4 derived stuff to home page
-- removed 'Acting' from Matt Payne
-- Ring node edits per forwarded email (Dec 23 2022)
> other edits

- data_sb/missions/ground.shtml
- data_sb/missions/hst/index.shtml
- data_sb/missions/orex/index.shtml
- data_sb/resources/release_sched.shtml
added datasets to other pages accordingly
> followup edits

- data_sb/comet_type.shtml
- data_sb/missions/rosetta/index.shtml
- data_sb/target_comets.shtml
- index.shtml
per email from Tilden, 16 Rosetta datasets on 4 pages
> Rosetta RPCMIP L5 2023-02-09 release

- css-n-includes/incl_top.inc
- data_other/Spitzer.shtml
- data_sb/comet_type.shtml
- data_sb/missions/dart/index.shtml
- data_sb/missions/rosetta/OSIRIS_cruise.shtml
- data_sb/missions/rosetta/index.shtml
- data_sb/missions/rosetta/index_RSI.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_comets.shtml
- data_sb/target_other.shtml
--  added downtime announcement
--  fixed some typos
--  big change was revising Rosetta dataset names that have US maneuver to British manoeuvre to be consistent; discussed and coordinated with TB
> downtime banner, misspellings

- about/MA_images/index.shtml
- about/comment_form.shtml
- about/comment_form_MPC.shtml
- about/contact_info.shtml
- about/links.shtml
- css-n-includes/incl_top.inc
- data_sb/lab_type.shtml
- data_sb/missions/hayabusa2/index.shtml
- data_sb/missions/rosetta/index_RSI.shtml
-- remove maintenance banner from Fri
-- minor edits to fix SiteImprove issues (alt tags, empty tags, ...)
> remove maintenance banner & other

- data_sb/comet_type.shtml
- data_sb/missions/dart/index.shtml
- data_sb/resources/coordinate_systems.shtml
- data_sb/target_asteroids.shtml
- index.shtml
v2 of Spacecraft bundle posted to pages, also coordinate system; announced on home page
> DART release

- data_sb/comet_type.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_other.shtml
> NH K5 update v5 to v6

- data_sb/by_mission.shtml
- data_sb/comet_type.shtml
- data_sb/missions/lucy/index.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_other.shtml
- index.shtml
fixed typos I made from editing at 2am in morning, mostly copy/paste issues. See emails from Tilden for details. Also some small edits of target names (replace Ultima Thule with Arrokoth, add MBA targets to Lucy)
> fix typos; other edits

- css-n-includes/site_editing_notes/mission_index_template.shtml
- data_sb/comet_type.shtml
- data_sb/missions/bopps/index.shtml
- data_sb/missions/cioc/index.shtml
- data_sb/missions/dart/index.shtml
- data_sb/missions/deepimpact/index.shtml
- data_sb/missions/deepspace1/index.shtml
- data_sb/missions/epoxi/index.shtml
- data_sb/missions/ground.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/missions/soho/index.shtml
- data_sb/resources/release_sched.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_comets.shtml
- data_sb/target_other.shtml
- index.shtml
-- per TB email re: NH Lorri COB release, added dataset and linked from several pages
-- fixed minor typo (added space between link and PDS4  urn code
> NH Lorri COB release

- data_sb/comet_type.shtml
- data_sb/missions/rosetta/index.shtml
- data_sb/resources/release_sched.shtml
- data_sb/target_comets.shtml
- index.shtml
per email from TB, R&A release of ROSINA DFMS Time Series Abundances
> ROSINA DFMS Time Series Abundances

- css-n-includes/incl_top.inc
> outage banner

- css-n-includes/incl_top.inc
overdue on removing maintenance banner
> remove maint banner

- css-n-includes/sbn_style.css
- data_sb/comet_type.shtml
- data_sb/missions/dart/index.shtml
- data_sb/target_asteroids.shtml
- index.shtml
2 bundles (7 collections) released
> DART and LICIACube S/C release

- data_sb/comet_type.shtml
- data_sb/missions/dart/index.shtml
- data_sb/target_asteroids.shtml
had forgotten to update the edit history
> updated edit history

- data_sb/comet_type.shtml
- data_sb/missions/dart/index.shtml
- data_sb/target_asteroids.shtml
- index.shtml
add bundle and 15 teleobs collections to DART and associated pages.
> DART Teleobs release

- data_sb/comet_type.shtml
- data_sb/missions/dart/index.shtml
- data_sb/target_asteroids.shtml
- index.shtml
Per TB et al, Didymos System Shape Model was made "publicly available"
> Didymos System Shape Model

- css-n-includes/incl_left-side.inc
Changed link in include file from local feedback form to MPC Help Center. (Overlooked an email from a long time ago!
> MPC feedback

- data_sb/missions/dart/index.shtml
added DART Spice to mission page
> DART Spice

- css-n-includes/incl_top.inc
> remove banner

- data_sb/comet_type.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_other.shtml
- index.shtml
replace pds3 NH KEM (documents, MVIC) datasets with pds4 collections
> NH migration

- data_sb/comet_type.shtml
NH Documents Bundle typo in name
> typo in bundle name

- about/contact_info.shtml
- about/links.shtml
- css-n-includes/incl_left-side.inc
- css-n-includes/site_editing_notes/mission_index_template.shtml
- data_sb/missions/deepimpact/index.shtml
- data_sb/missions/epoxi/index.shtml
- data_sb/missions/hst/index.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/missions/soho/index.shtml
-- removed or fixed dead links found using SiteImprove
-- spelling fixes
> SiteImprove edits

- data_sb/comet_type.shtml
- data_sb/lab_type.shtml
- data_sb/missions/ground.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_other.shtml
- index.shtml
-- Per email from Tilden, posted 2 R&A datasets to several pages. Pluto albedo Map and CLASSE Charon 
-- minor typos
> Release of 2 R&A datasets

- data_sb/comet_type.shtml
- data_sb/lab_type.shtml
- data_sb/missions/ground.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_other.shtml
- index.shtml
per email from Tilden, fixed the mix up of where the Pluto Albedo and CLASSE Charon datasets were initially posted.
> fixed mixup of Pluto Albedo and CLASSE Charon

- data_sb/comet_type.shtml
- data_sb/missions/lucy/index.shtml
- data_sb/target_asteroids.shtml
- index.shtml
per emails from TB, updated the Lucy Mission page and added bundle and components.
> Lucy Didymos data release

- data_sb/comet_type.shtml
- data_sb/missions/lucy/index.shtml
- data_sb/target_asteroids.shtml
- index.shtml
fixed typo in Lucy-Didymos links (missing "/")
> fixed typo

- data_sb/comet_type.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_other.shtml
- index.shtml
replaced/added various PDS4 bundles and collections per email from TB
> NH KEM1 PDS4 release

- data_sb/comet_type.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_other.shtml
- index.shtml
per email from Tilden, replaced/added PDS4 files
> nh_leisa migration release 2024-08-30

- data_sb/comet_type.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_asteroids.shtml
- index.shtml
Per 4 Oct email from Tilden, release of Arrokoth Shape Model
> Arrokoth Shape Model release

- data_sb/comet_type.shtml
- data_sb/missions/lucy/index.shtml
- data_sb/target_asteroids.shtml
- index.shtml
> Lucy Dinkinesh and older  Arrokoth shape

- index.shtml
Cleaned up the presentation of the Lucy Dinkinesh release
> Cleaned up release listing for Lucy Dinkinesh

- index.shtml
Sorry, minor tweak to fix bundle-collection relationship in Lucy Dinkinesh release
> another minor tweak

- data_sb/resources/release_sched.shtml
release_sched.shtml -- forgot to make minor word edit in intor that TB had asked for
> minor word tweak

- data_sb/missions/deepimpact/index.shtml
> remove test edit

- css-n-includes/incl_top.inc
- data_sb/missions/newhorizons/index.shtml
-- per email from Tilden, fixed minor typo on the NH page in link text going to NH KEM 
-- network outage banner for network refresh over weekend
> minor typo and Network outage banner

- css-n-includes/incl_top.inc
- css-n-includes/sbn_style.css
-- trying to get maintenance banner to show up better -- added EST
> minor tweaks

- data_sb/comet_type.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_other.shtml
- index.shtml
Per email from TFB, posted migration datasets
> NH K5 migration

- data_sb/by_mission.shtml
Forgot to add link after making ATLAS page
> Forgot link

- data_sb/missions/atlas/index.shtml
trying to get the okina symbol coding correct
> okina symbol

- data_sb/missions/atlas/index.shtml
> Update ATLAS index.shtml

- data_sb/comet_type.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_other.shtml
- index.shtml
> nh_pepssi K5 migration

- index.shtml
> index.shtml

- css-n-includes/incl_top.inc
banner for 16 March network outage
> service banner

- about/links.shtml
- css-n-includes/incl_top.inc
removed maintenance banner; added several books to the reference list on our links page
> removed banner; books

- data_sb/comet_type.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_asteroids.shtml
- index.shtml
Migrated LEISSA, MVIC, SDC datasets per email from Tilden
> migration per TB

- data_sb/comet_type.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_other.shtml
- index.shtml
Per TB email, NH Alice migration release
> nh_alice PE migration release

- data_sb/comet_type.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_other.shtml
- index.shtml
Per email from TB nh_pepssi PE migration release 2025-06-16
> NH PEPSSI migration

- data_sb/comet_type.shtml
- data_sb/missions/soho/index.shtml
- data_sb/target_comets.shtml
- index.shtml
> SOHO SWAN derived v4.0

- index.shtml
per email from TB, minor edit to formatting
> minor edit to formatting of data release

- data_sb/comet_type.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/missions/nh-kem/index.shtml
- data_sb/target_asteroids.shtml
- data_sb/target_other.shtml
- index.shtml
NH Derived migration release 2025-07-01
> per TFB email

- data_sb/comet_type.shtml
- data_sb/missions/newhorizons/index.shtml
- data_sb/target_other.shtml
- index.shtml
> NH SWAP migration

- index.shtml
- proposals/ROSES.shtml
- proposals/ROSES2025.shtml
spelling; minor edits to ROSES; per emails from TB and LK
> minor edits
